import hashlib
import argparse


def sha256_short(s: str) -> str:
    """Returns first 8 characters in SHA256 hash of `s`."""
    return hashlib.sha256(s.encode()).hexdigest()[:8]


def find_emails_by_hashes(input_file, output_file, target_hashes):
    # 1. Create a dictionary to map hashes back to emails
    # Key: hash string, Value: original email
    hash_map = {}

    try:
        with open(input_file, "r") as f:
            for line in f:
                email = line.strip()
                if email:
                    # Compute hash and store in map
                    h = sha256_short(email)
                    hash_map[h] = email

        # 2. Identify which original emails match our target hash list
        matched_emails = []
        for h in target_hashes:
            if h in hash_map:
                matched_emails.append(hash_map[h])
            else:
                print(f"Warning: No email found for hash {h}")

        # 3. Write the results to a new file
        with open(output_file, "w") as f:
            for email in matched_emails:
                f.write(f"{email}\n")

        print(f"Successfully recovered {len(matched_emails)} emails to {output_file}")

    except FileNotFoundError:
        print(f"Error: The file '{input_file}' or '{output_file}' was not found.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Email Hash Lookup",
        description="Given a list of student email hashes generated by the backups CLI and a list of all student emails, retrieve the emails of students with those target hashes.",
    )

    parser.add_argument(
        "hashes",
        type=str,
        help="Path to target student email hashes .txt file (one hash per line)",
    )
    parser.add_argument(
        "input", type=str, help="Path to input emails .txt file (one email per line)"
    )
    parser.add_argument(
        "output",
        type=str,
        help="Path to output emails .txt file (writes one email per line)",
    )

    args = parser.parse_args()

    assert args.hashes.endswith(".txt")
    assert args.input.endswith(".txt")
    assert args.output.endswith(".txt")

    find_emails_by_hashes(
        input_file=args.input,
        output_file=args.output,
        target_hashes=args.hashes,
    )
