name: rubocop

on: [push]

jobs:
  lint:
    env:
      backend-directory: src/app/server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{env.backend-directory}}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: rubocop
        run: |
          cd ${{env.backend-directory}}
          bundle exec rubocop -f github
